PATH_TRAINING = ../data/YAGO3-10/data/YAGO3-10_train.tsv
PATH_VALID    = ../data/YAGO3-10/data/YAGO3-10_valid.tsv
PATH_TEST     = ../data/YAGO3-10/data/YAGO3-10_test.tsv

PATH_OUTPUT = ../data/YAGO3-10/predictions/YAGO3-10_anyburl-predictions

PATH_RULES    = ../data/YAGO3-10/rules/YAGO3-10_rules_anyburl-1000

WORKER_THREADS = 8

TOP_K_OUTPUT = 100