PATH_TRAINING = datasets/hetionet/data/hetio_train_nice.tsv
PATH_VALID    = datasets/hetionet/data/hetio_validation_nice.tsv
PATH_TEST     = datasets/hetionet/data/hetio_test_nice.tsv

PATH_PREDICTIONS = datasets/hetionet/predictions/hetionet_original_anyburl_predictions




TOP_K_OUTPUT = 100