PATH_TRAINING = ../data/hetionet/data/hetionet_train.tsv
PATH_VALID    = ../data/hetionet/data/hetionet_validation.tsv
PATH_TEST     = ../data/hetionet/data/hetionet_test.tsv

PATH_OUTPUT = ../data/hetionet/predictions/hetionet_original_anyburl_predictions

PATH_RULES    =../data/hetionet/rules/hetionet_rules_anyburl-1000


WORKER_THREADS = 16

TOP_K_OUTPUT = 100