#PATH_TRAINING = ../data/OWL2Bench/data/OWL2Bench_train.tsv
PATH_TRAINING = ./setup/OWL2Bench/OWL2Bench_train.tsv

PATH_OUTPUT   =./setup/OWL2Bench/OWL2Bench_rules_anyburl_CP
#PATH_OUTPUT   = ../data/OWL2Bench/rules/OWL2Bench_rules_anyburl_CP
SNAPSHOTS_AT = 100

WORKER_THREADS = 1

THRESHOLD_CONFIDENCE = 0.1

THRESHOLD_CORRECT_PREDICTIONS = 2

MAX_LENGTH_ACYCLIC = 0

MAX_LENGTH_GROUNDED_CYCLIC = 0

MAX_LENGTH_CYCLIC = 3
ZERO_RULES_ACTIVE = false
REWRITE_REFLEXIV = false 
SAFE_PREFIX_MODE = true 
x