PATH_TRAINING = datasets/CSKG2/data/CSKG2_train.tsv
PATH_VALID    = datasets/CSKG2/data/CSKG2_valid.tsv
PATH_TEST     = datasets/CSKG2/data/CSKG2_test.tsv

PATH_PREDICTIONS = datasets/CSKG2/predictions/CSKG2_original_anyburl_predictions




TOP_K_OUTPUT = 100