PATH_TRAINING = data/CSKG2/data/CSKG2_train.tsv
PATH_VALID    = data/CSKG2/data/CSKG2_valid.tsv
PATH_TEST     = data/CSKG2/data/CSKG2_test.tsv

PATH_OUTPUT = data/CSKG2/predictions/CSKG2_original_anyburl_predictions

PATH_RULES    = data/CSKG2/rules/CSKG2_rules_anyburl-1000


WORKER_THREADS = 16

TOP_K_OUTPUT = 100