PATH_TRAINING = ../data/NELL995/data/NELL995_train.tsv
PATH_VALID    = ../data/NELL995/data/NELL995_valid.tsv
PATH_TEST     = ../data/NELL995/data/NELL995_test.tsv

#PATH_PREDICTIONS = ../data/NELL995/predictions/predictions.txt
PATH_PREDICTIONS = ../data/NELL995/predictions/latest_predictions.txt




TOP_K_OUTPUT = 100