PATH_TRAINING = ../data/NELL995/data/NELL995_train.tsv

PATH_OUTPUT   = ../data/NELL995/rules/NELL995_rules_anyburl_CP

SNAPSHOTS_AT = 100

WORKER_THREADS = 1

THRESHOLD_CONFIDENCE = 0.1

THRESHOLD_CORRECT_PREDICTIONS = 2

MAX_LENGTH_ACYCLIC = 0

MAX_LENGTH_GROUNDED_CYCLIC = 0

MAX_LENGTH_CYCLIC = 3
ZERO_RULES_ACTIVE = false
REWRITE_REFLEXIV = false 
SAFE_PREFIX_MODE = true 
x