PATH_TRAINING = ../data/NELL995/data/NELL995_train.tsv
PATH_VALID    = ../data/NELL995/data/NELL995_valid.tsv
PATH_TEST     = ../data/NELL995/data/NELL995_test.tsv


PATH_RULES    = ../data/NELL995/rules/NELL995_rules_anyburl-1000
PATH_OUTPUT = ../data/NELL995/predictions/predictions.txt




WORKER_THREADS = 10

TOP_K_OUTPUT = 100