PATH_TRAINING = datasets/YAGO4.5/data/YAGO4.5-10_train.tsv
PATH_VALID    = datasets/YAGO4.5/data/YAGO4.5-10_valid.tsv
PATH_TEST     = datasets/YAGO4.5/data/YAGO4.5-10_test.tsv
PATH_PREDICTIONS =  datasets/YAGO4.5/predictions/YAGO4-5-10_anyburl-predictions




TOP_K_OUTPUT = 100