PATH_TRAINING = datasets/YAGO4.5/data/YAGO4.5-10_train.tsv
PATH_VALID    = datasets/YAGO4.5/data/YAGO4.5-10_valid.tsv
PATH_TEST     = datasets/YAGO4.5/data/YAGO4.5-10_test.tsv

PATH_OUTPUT = datasets/YAGO4.5/predictions/YAGO4-5-10_anyburl-predictions

PATH_RULES    = datasets/YAGO4.5/rules/YAGO4.5_rules_anyburl-1000

WORKER_THREADS = 1

TOP_K_OUTPUT = 100